### PR TITLE
Switch to jpg for better compression

### PR DESCRIPTION
**Pull request by siakaramalegos**
Hi I used squoosh.app to convert to jpg for smaller file sizes. Also changed out my profile pic since that was the original impetus for the PR. :)

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Thank you, Sia! One question — could we automate the squooshing for new images, do you think?

**Comment by siakaramalegos** [comment]
They don't have a CLI yet, but we could also use another image solution. Might be better to chat about some options - like using the twitter avatar URL instead or if we do actual files, using eleventy image or cloudinary.

**Comment by whitep4nth3r** [comment]
Optimising images is on my to do list anyway, so I'll merge this for now! Thank you!

**Comment by siakaramalegos** [comment]
Let me know if you want any help!

**Pull request merged**
