### PR TITLE
Aisha Khan Profile 

### PR DESCRIPTION
**Pull request by aishakhan0925**

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Hey there, thank you for your profile! Would you be able to add a square image without white strips on each side please?

**Comment by aishakhan0925** [comment]
Hey,

Thank you very much for notifying me. Yes, I will open a pull request
shortly.

**Comment by aishakhan0925** [comment]
> Hey there, thank you for your profile! Would you be able to add a square image without white strips on each side please?

Hey i updated the pull request, please have a look on it, Many Thanks.

**Comment by whitep4nth3r** [comment]
Thank you!

**Pull request merged**
