### PR TITLE
Add Elaine May

### PR DESCRIPTION
**Pull request by elmay-netlify**
Add Elaine May from Netlify to "Women of Jamstack" page.

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Thanks Elaine! You'll need to remove the comments from your JSON file (//optional) and then you'll be good to go!

**Comment by whitep4nth3r** [comment]
JSON is picky and doesn't like commas on the last lines of objects... so you'll need to remove that please 😉 I need to check if I need to update the docs.

**Comment by whitep4nth3r** [comment]
Docs are all good. No comma on last line!

**Comment by elmay-netlify** [comment]
Trying this again from the beginning :).

**Comment by whitep4nth3r** [comment]
I just merged it because I wasn't paying attention but the comma on the last line will fail the merge 😅😅😅 I'll fix it next week!

**Pull request closed without merging**
